// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaz1cjnQMG_nc8USVlIX-SxkVEPx4Ygps',
    appId: '1:817751276557:web:af54b5279dffc1bae42944',
    messagingSenderId: '817751276557',
    projectId: 'loja-agata-dds1',
    authDomain: 'loja-agata-dds1.firebaseapp.com',
    storageBucket: 'loja-agata-dds1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGPEsvGUPC4hc6has9p0-9JozVgfLMJ7M',
    appId: '1:817751276557:android:586d869edc038855e42944',
    messagingSenderId: '817751276557',
    projectId: 'loja-agata-dds1',
    storageBucket: 'loja-agata-dds1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2QxahMGnJxhEaDzN72Jo4lvyyifqJP58',
    appId: '1:817751276557:ios:e4ebd047a6914e65e42944',
    messagingSenderId: '817751276557',
    projectId: 'loja-agata-dds1',
    storageBucket: 'loja-agata-dds1.appspot.com',
    iosClientId: '817751276557-1pi0rdb21l29ggpmvf736ttho0v24t0k.apps.googleusercontent.com',
    iosBundleId: 'br.com.dds.agataApp',
  );
}
